### ISSUE TITLE
[反馈]: 游戏导航页面，多个 icon 无法加载

### ISSUE THREAD

**Issue by xiamiko** [GlacierLab/KumoNavigate#1]
经过 devtool 检查，部分 icon 域外访问会被跳转，部分 icon 已经 404。

无法加载的 icon 包括：
- [Origin](https://www.origin.com/)
- [Valorant](https://playvalorant.com/)
- [Special K](https://discourse.differentk.fyi/)
- [Cocos Engine](https://www.cocos.com/)
- [Egret Engine](https://docs.egret.com/engine/)

环境信息：
- Windows11
- Microsoft Edge 版本 111.0.1661.41 (正式版本) (64 位)
- Proxy via Hong Kong

![image](https://user-images.githubusercontent.com/65271470/237047081-a8c2f189-41d1-4e4a-9d6f-a051909b3e3d.png)

![image](https://user-images.githubusercontent.com/65271470/237047252-cea3ec79-0ca0-4aac-9d80-bd33a348fdd8.png)

**Comment by qinlili23333** [comment]
收到！正在处理

**Comment by qinlili23333** [comment]
已部分修复，Egret Engine主站证书过期目前无解
